spring:

  datasource:
    url: jdbc:mysql://localhost:3306/ynv
    username: root
    password: dev12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      '[hibernate.format_sql]': true

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never

ynv:
  app:
    jwtSecret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
    jwtExpirationMs: 86400000 # a day
#    refresh-token:
#      expiration: 604800000 # 7 days


